# Generated by Django 2.2.12 on 2022-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20220509_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='qur',
            name='uid',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
