# Generated by Django 2.2.12 on 2022-05-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_qur_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='qur',
            name='subject',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
