# Generated by Django 2.2.12 on 2022-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_qur_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='qur',
            name='message',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
