# Generated by Django 2.2.12 on 2022-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_qur_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='multi_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40)),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='')),
                ('file4', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
